import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Privacy Policy for ToolsShed — how we handle your data.",
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "February 21, 2026";

export default function PrivacyPolicyPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
      <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
      <p className="text-gray-500 text-sm mb-10">Last updated: {LAST_UPDATED}</p>

      <div className="prose prose-invert max-w-none space-y-8 text-gray-300 leading-relaxed">

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">Overview</h2>
          <p>
            ToolsShed (&quot;we&quot;, &quot;us&quot;, or &quot;our&quot;) operates the website{" "}
            <a href="https://tools-shed.com" className="text-indigo-400 hover:underline">
              tools-shed.com
            </a>
            . This page informs you of our policies regarding the collection, use, and disclosure
            of personal information when you use our service.
          </p>
          <p className="mt-3">
            <strong className="text-white">The short version:</strong> All tools on ToolsShed run
            entirely in your browser. We do not store, transmit, or process any data you enter
            into our tools on our servers.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">1. Data We Do NOT Collect</h2>
          <p>ToolsShed tools operate entirely client-side. This means:</p>
          <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
            <li>Text you paste into JSON Formatter, Base64, or any other tool</li>
            <li>Passwords generated by the Password Generator</li>
            <li>Health data entered into the BMI Calculator</li>
            <li>Financial data entered into calculators</li>
            <li>Any other input you provide to our tools</li>
          </ul>
          <p className="mt-3">
            None of this data ever leaves your device or is sent to any server.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">2. Google Analytics</h2>
          <p>
            We use Google Analytics 4 to understand how visitors interact with our site
            (e.g., which tools are most popular, how long visitors stay, which countries
            visitors come from). This data is anonymous and aggregated.
          </p>
          <p className="mt-3">Google Analytics may collect:</p>
          <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
            <li>Pages visited and time spent</li>
            <li>General geographic location (country/city level)</li>
            <li>Browser type and device type</li>
            <li>Referring website</li>
          </ul>
          <p className="mt-3">
            Google Analytics uses cookies. You can opt out by installing the{" "}
            <a
              href="https://tools.google.com/dlpage/gaoptout"
              target="_blank"
              rel="noopener noreferrer"
              className="text-indigo-400 hover:underline"
            >
              Google Analytics Opt-out Browser Add-on
            </a>
            .
          </p>
          <p className="mt-3">
            For more information, see{" "}
            <a
              href="https://policies.google.com/privacy"
              target="_blank"
              rel="noopener noreferrer"
              className="text-indigo-400 hover:underline"
            >
              Google&apos;s Privacy Policy
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">3. Google AdSense</h2>
          <p>
            We use Google AdSense to display advertisements. Google AdSense uses cookies to
            serve ads based on your prior visits to our website or other websites on the internet.
          </p>
          <p className="mt-3">
            Google&apos;s use of advertising cookies enables it and its partners to serve ads based
            on your visit to our site and/or other sites on the internet. You may opt out of
            personalized advertising by visiting{" "}
            <a
              href="https://www.google.com/settings/ads"
              target="_blank"
              rel="noopener noreferrer"
              className="text-indigo-400 hover:underline"
            >
              Google Ads Settings
            </a>
            .
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">4. Comments (Giscus)</h2>
          <p>
            Our comment system is powered by{" "}
            <a
              href="https://giscus.app"
              target="_blank"
              rel="noopener noreferrer"
              className="text-indigo-400 hover:underline"
            >
              Giscus
            </a>
            , which stores comments as GitHub Discussions. If you choose to leave a comment,
            you must sign in with a GitHub account. Your comment and GitHub profile information
            will be publicly visible on GitHub.
          </p>
          <p className="mt-3">
            See{" "}
            <a
              href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement"
              target="_blank"
              rel="noopener noreferrer"
              className="text-indigo-400 hover:underline"
            >
              GitHub&apos;s Privacy Statement
            </a>{" "}
            for details.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">5. Cookies</h2>
          <p>We use the following types of cookies:</p>
          <div className="mt-3 overflow-x-auto">
            <table className="w-full text-sm border border-gray-700 rounded-lg overflow-hidden">
              <thead>
                <tr className="bg-gray-800">
                  <th className="text-left px-4 py-2 text-gray-300">Cookie</th>
                  <th className="text-left px-4 py-2 text-gray-300">Purpose</th>
                  <th className="text-left px-4 py-2 text-gray-300">Provider</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-700">
                <tr className="bg-gray-900">
                  <td className="px-4 py-2 font-mono text-gray-400">_ga, _ga_*</td>
                  <td className="px-4 py-2 text-gray-400">Analytics tracking</td>
                  <td className="px-4 py-2 text-gray-400">Google Analytics</td>
                </tr>
                <tr className="bg-gray-900">
                  <td className="px-4 py-2 font-mono text-gray-400">IDE, NID</td>
                  <td className="px-4 py-2 text-gray-400">Ad personalization</td>
                  <td className="px-4 py-2 text-gray-400">Google AdSense</td>
                </tr>
              </tbody>
            </table>
          </div>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">6. Third-Party Links</h2>
          <p>
            Our website may contain links to external sites. We are not responsible for the
            privacy practices or content of those sites. We encourage you to review the
            privacy policies of any external sites you visit.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">7. Children&apos;s Privacy</h2>
          <p>
            ToolsShed is not directed to children under the age of 13. We do not knowingly
            collect personal information from children under 13.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">8. Changes to This Policy</h2>
          <p>
            We may update this Privacy Policy from time to time. Changes will be posted on
            this page with an updated &quot;Last updated&quot; date. Continued use of the site after
            changes constitutes acceptance of the updated policy.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">9. Contact</h2>
          <p>
            If you have any questions about this Privacy Policy, please open an issue on our{" "}
            <a
              href="https://github.com/hasune/tools-shed"
              target="_blank"
              rel="noopener noreferrer"
              className="text-indigo-400 hover:underline"
            >
              GitHub repository
            </a>
            .
          </p>
        </section>

      </div>

      <div className="mt-12 pt-6 border-t border-gray-800">
        <Link href="/" className="text-indigo-400 hover:text-indigo-300 text-sm transition-colors">
          ← Back to Tools
        </Link>
      </div>
    </div>
  );
}
