export interface Tool {
  slug: string;
  name: string;
  description: string;
  category: string;
  categorySlug: string;
  icon: string;
  keywords: string[];
}

export interface Category {
  slug: string;
  name: string;
  description: string;
  icon: string;
  tools: Tool[];
}

export const tools: Tool[] = [
  // Developer Tools
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "{ }",
    keywords: ["json", "format", "validate", "beautify", "minify", "pretty print"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4) for use in your applications.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "🔑",
    keywords: ["uuid", "guid", "unique", "identifier", "random", "v4"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode text or files to Base64 and decode Base64 strings.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "64",
    keywords: ["base64", "encode", "decode", "binary", "text"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode and decode URLs and query parameters for safe transmission.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "🔗",
    keywords: ["url", "encode", "decode", "percent", "uri", "query string"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-256, and SHA-512 cryptographic hashes.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "#",
    keywords: ["hash", "md5", "sha256", "sha512", "checksum", "crypto"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Token payloads without signature verification.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "JWT",
    keywords: ["jwt", "json web token", "decode", "payload", "auth", "bearer"],
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, and HSL formats instantly.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "🎨",
    keywords: ["color", "hex", "rgb", "hsl", "converter", "palette", "css color"],
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "01",
    keywords: ["binary", "octal", "decimal", "hexadecimal", "base", "convert", "number base"],
  },
  {
    slug: "regex-tester",
    name: "RegEx Tester",
    description: "Test and debug regular expressions with live match highlighting.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: ".*",
    keywords: ["regex", "regular expression", "test", "match", "pattern", "debug"],
  },
  {
    slug: "csv-json",
    name: "CSV ↔ JSON Converter",
    description: "Convert CSV data to JSON and JSON arrays back to CSV format.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "CSV",
    keywords: ["csv", "json", "convert", "data", "spreadsheet", "table"],
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and highlight the differences line by line.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "±",
    keywords: ["diff", "compare", "text", "difference", "changes", "patch"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text for design and development.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "¶",
    keywords: ["lorem ipsum", "placeholder", "text", "generate", "dummy", "filler"],
  },
  {
    slug: "html-encoder",
    name: "HTML Encoder / Decoder",
    description: "Encode special characters to HTML entities and decode them back.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "</>",
    keywords: ["html", "encode", "decode", "entities", "escape", "unescape"],
  },
  {
    slug: "yaml-json",
    name: "YAML ↔ JSON Converter",
    description: "Convert between YAML and JSON formats instantly.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "⇌",
    keywords: ["yaml", "json", "convert", "configuration", "config", "devops"],
  },
  // Unit Converters
  {
    slug: "length-converter",
    name: "Length Converter",
    description: "Convert between meters, feet, inches, miles, kilometers, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "📏",
    keywords: ["length", "convert", "meter", "feet", "inch", "mile", "kilometer"],
  },
  {
    slug: "weight-converter",
    name: "Weight Converter",
    description: "Convert between kilograms, pounds, ounces, grams, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "⚖️",
    keywords: ["weight", "mass", "kg", "lbs", "ounce", "gram", "convert"],
  },
  {
    slug: "temperature-converter",
    name: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "🌡️",
    keywords: ["temperature", "celsius", "fahrenheit", "kelvin", "convert"],
  },
  {
    slug: "data-storage-converter",
    name: "Data Storage Converter",
    description: "Convert between bytes, kilobytes, megabytes, gigabytes, terabytes, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "💾",
    keywords: ["bytes", "kb", "mb", "gb", "tb", "storage", "convert", "data size"],
  },
  {
    slug: "speed-converter",
    name: "Speed Converter",
    description: "Convert between km/h, mph, m/s, knots, and other speed units.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "🚀",
    keywords: ["speed", "velocity", "km/h", "mph", "m/s", "knots", "convert"],
  },
  {
    slug: "area-converter",
    name: "Area Converter",
    description: "Convert between square meters, square feet, acres, hectares, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "⬜",
    keywords: ["area", "square meter", "square foot", "acre", "hectare", "convert"],
  },
  {
    slug: "volume-converter",
    name: "Volume Converter",
    description: "Convert between liters, gallons, fluid ounces, cubic meters, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "🧊",
    keywords: ["volume", "liter", "gallon", "fluid ounce", "cubic meter", "convert"],
  },
  // Text Tools
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    description: "Count words, characters, sentences, and paragraphs in your text.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "✍️",
    keywords: ["word count", "character count", "text", "counter", "writing"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text to UPPERCASE, lowercase, Title Case, camelCase, and more.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "Aa",
    keywords: ["case", "uppercase", "lowercase", "title case", "camelcase", "text convert"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords with customizable options.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🔒",
    keywords: ["password", "generate", "secure", "random", "strong", "security"],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write Markdown and preview the rendered output in real time.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "MD",
    keywords: ["markdown", "preview", "render", "html", "editor", "md"],
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Convert any text into a clean, URL-friendly slug.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🔗",
    keywords: ["slug", "url", "permalink", "seo", "text", "convert"],
  },
  {
    slug: "text-repeater",
    name: "Text Repeater",
    description: "Repeat any text or character a specified number of times.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "↺",
    keywords: ["repeat", "text", "duplicate", "loop", "generator"],
  },
  // Finance Tools
  {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    description: "Calculate compound interest growth for investments over time.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "📈",
    keywords: ["compound interest", "investment", "calculator", "finance", "savings"],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, percentage change, and tip amounts.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "%",
    keywords: ["percentage", "percent", "tip", "calculator", "math"],
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    description: "Calculate sale prices, discount amounts, and savings instantly.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "🏷️",
    keywords: ["discount", "sale", "price", "savings", "percent off", "calculator"],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate monthly payments, total interest, and amortization for loans.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "🏦",
    keywords: ["loan", "mortgage", "payment", "interest", "amortization", "calculator"],
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    description: "Calculate return on investment and annualized ROI for any investment.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "📊",
    keywords: ["roi", "return on investment", "profit", "investment", "calculator"],
  },
  // Health Tools
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate Body Mass Index with metric and imperial units.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🏃",
    keywords: ["bmi", "body mass index", "health", "weight", "height"],
  },
  {
    slug: "tdee-calculator",
    name: "TDEE Calculator",
    description: "Calculate your Total Daily Energy Expenditure and daily calorie needs.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🔥",
    keywords: ["tdee", "calories", "bmr", "energy", "diet", "nutrition", "calculator"],
  },
  {
    slug: "ideal-weight",
    name: "Ideal Weight Calculator",
    description: "Calculate your ideal body weight based on height using multiple formulas.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "⚖️",
    keywords: ["ideal weight", "healthy weight", "bmi", "height", "calculator"],
  },
  {
    slug: "body-fat",
    name: "Body Fat Calculator",
    description: "Estimate body fat percentage using the U.S. Navy method.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "📐",
    keywords: ["body fat", "body fat percentage", "navy method", "fitness", "calculator"],
  },
  // Time Tools
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, and days from a birth date.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🎂",
    keywords: ["age", "birthday", "date", "calculate", "years", "months"],
  },
  {
    slug: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert time between different time zones around the world.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🌍",
    keywords: ["timezone", "time zone", "convert", "world time", "utc", "gmt"],
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "⏱️",
    keywords: ["unix", "timestamp", "epoch", "date", "convert", "time", "posix"],
  },
  {
    slug: "date-difference",
    name: "Date Difference Calculator",
    description: "Calculate the exact number of days, weeks, and months between two dates.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "📅",
    keywords: ["date", "difference", "days between", "calculate", "calendar", "duration"],
  },
  {
    slug: "time-duration",
    name: "Time Duration Calculator",
    description: "Add or subtract hours, minutes, and seconds to calculate time durations.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "⏳",
    keywords: ["time", "duration", "hours", "minutes", "seconds", "add", "subtract"],
  },
  // Math Tools
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    description: "Advanced calculator with trigonometry, logarithms, powers, and more.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "🧮",
    keywords: ["calculator", "scientific", "sin", "cos", "tan", "log", "sqrt", "math"],
  },
  {
    slug: "gcd-lcm",
    name: "GCD & LCM Calculator",
    description: "Calculate the Greatest Common Divisor and Least Common Multiple of multiple numbers.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "÷",
    keywords: ["gcd", "lcm", "greatest common divisor", "least common multiple", "math", "number theory"],
  },
  {
    slug: "quadratic-solver",
    name: "Quadratic Equation Solver",
    description: "Solve quadratic equations ax² + bx + c = 0 with step-by-step solutions.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "x²",
    keywords: ["quadratic", "equation", "solver", "roots", "discriminant", "polynomial", "math"],
  },
  // Developer (new batch)
  {
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description: "Parse and explain cron expressions with next scheduled execution times.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "⏱",
    keywords: ["cron", "crontab", "schedule", "expression", "parse", "unix", "linux"],
  },
  {
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Convert JSON objects to TypeScript interfaces automatically.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "TS",
    keywords: ["json", "typescript", "interface", "type", "convert", "schema", "generate"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries for better readability.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "SQL",
    keywords: ["sql", "format", "query", "beautify", "database", "indent"],
  },
  {
    slug: "string-escape",
    name: "String Escape / Unescape",
    description: "Escape and unescape strings for JSON, JavaScript, and HTML contexts.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\\n",
    keywords: ["escape", "unescape", "string", "json", "javascript", "html", "backslash"],
  },
  // Text (new batch)
  {
    slug: "text-to-binary",
    name: "Text to Binary / Hex",
    description: "Convert text to binary, hexadecimal, octal, and decimal encodings.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "01",
    keywords: ["binary", "hex", "hexadecimal", "text", "convert", "encode", "ascii", "octal"],
  },
  {
    slug: "random-name-generator",
    name: "Random Name Generator",
    description: "Generate random first names, last names, or full names for testing and placeholders.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "👤",
    keywords: ["name", "random", "generate", "first name", "last name", "fake", "placeholder"],
  },
  // Finance (new batch)
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tip amounts and split the bill between multiple people.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "💵",
    keywords: ["tip", "bill", "split", "restaurant", "calculator", "gratuity", "per person"],
  },
  // Math (new batch)
  {
    slug: "statistics-calculator",
    name: "Statistics Calculator",
    description: "Calculate mean, median, mode, standard deviation, variance, and more.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "σ",
    keywords: ["statistics", "mean", "median", "mode", "standard deviation", "variance", "calculator"],
  },
  {
    slug: "fraction-calculator",
    name: "Fraction Calculator",
    description: "Add, subtract, multiply, and divide fractions with step-by-step solutions.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "½",
    keywords: ["fraction", "numerator", "denominator", "add", "subtract", "multiply", "divide", "simplify"],
  },
  {
    slug: "roman-numeral-converter",
    name: "Roman Numeral Converter",
    description: "Convert between Arabic numbers and Roman numerals instantly.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "Ⅻ",
    keywords: ["roman numeral", "arabic", "convert", "number", "roman"],
  },
  // Developer (new batch 2)
  {
    slug: "number-to-words",
    name: "Number to Words",
    description: "Convert numbers to English words (e.g. 1234 → one thousand two hundred thirty-four).",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "123",
    keywords: ["number", "words", "convert", "english", "spell", "write out"],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate complementary, analogous, triadic, and other color palettes from a base color.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "🎨",
    keywords: ["color", "palette", "complementary", "analogous", "triadic", "hsl", "hex", "design"],
  },
  {
    slug: "image-to-base64",
    name: "Image to Base64",
    description: "Convert image files to Base64 data URLs for embedding in HTML or CSS.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "🖼",
    keywords: ["image", "base64", "data url", "convert", "encode", "embed", "png", "jpg"],
  },
  // Text (new batch 2)
  {
    slug: "text-sorter",
    name: "Text Sorter",
    description: "Sort lines of text alphabetically, by length, or randomly.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "↕",
    keywords: ["sort", "text", "lines", "alphabetical", "order", "arrange"],
  },
  {
    slug: "emoji-picker",
    name: "Emoji Picker",
    description: "Browse, search, and copy emojis to your clipboard instantly.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "😀",
    keywords: ["emoji", "picker", "copy", "search", "unicode", "emoticon"],
  },
  {
    slug: "line-deduplicator",
    name: "Line Deduplicator",
    description: "Remove duplicate lines from text with options for case sensitivity and sorting.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "⊟",
    keywords: ["duplicate", "lines", "remove", "unique", "deduplicate", "text"],
  },
  // Developer (new batch 3)
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from any text or URL instantly.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "▦",
    keywords: ["qr code", "qr", "barcode", "generate", "url", "text", "scan"],
  },
  {
    slug: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    description: "Calculate aspect ratios and scale dimensions while maintaining proportions.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "⬚",
    keywords: ["aspect ratio", "resolution", "width", "height", "scale", "16:9", "4:3"],
  },
  {
    slug: "color-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Create beautiful CSS linear and radial gradients with a visual editor.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "🌈",
    keywords: ["gradient", "css", "linear", "radial", "color", "background", "generator"],
  },
  {
    slug: "morse-code-converter",
    name: "Morse Code Converter",
    description: "Convert text to Morse code and decode Morse code back to text.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "·−",
    keywords: ["morse code", "morse", "convert", "encode", "decode", "dots", "dashes"],
  },
  // Math (new batch 2)
  {
    slug: "prime-factorizer",
    name: "Prime Checker & Factorizer",
    description: "Check if a number is prime and find its prime factorization.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "ℙ",
    keywords: ["prime", "factor", "factorization", "prime number", "sieve", "divisor"],
  },
  {
    slug: "matrix-calculator",
    name: "Matrix Calculator",
    description: "Add, multiply, transpose, and find the determinant of 2×2 and 3×3 matrices.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "⊞",
    keywords: ["matrix", "determinant", "multiply", "transpose", "inverse", "linear algebra"],
  },
  {
    slug: "number-sequence",
    name: "Number Sequence Generator",
    description: "Generate arithmetic, geometric, Fibonacci, and prime number sequences.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "…",
    keywords: ["sequence", "arithmetic", "geometric", "fibonacci", "prime", "series", "pattern"],
  },
  {
    slug: "proportion-solver",
    name: "Proportion Solver",
    description: "Solve proportions and ratios — find the missing value in a/b = c/d.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "∝",
    keywords: ["proportion", "ratio", "solve", "cross multiply", "a/b=c/d", "missing value"],
  },
  // Health (new batch)
  {
    slug: "running-pace",
    name: "Running Pace Calculator",
    description: "Calculate running pace, speed, time, and distance for any race distance.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🏃",
    keywords: ["running", "pace", "marathon", "5k", "10k", "speed", "distance", "time", "race"],
  },
  {
    slug: "water-intake",
    name: "Water Intake Calculator",
    description: "Calculate your recommended daily water intake based on weight and activity level.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "💧",
    keywords: ["water", "hydration", "intake", "daily", "health", "calculator", "drink"],
  },
  // Time (new batch)
  {
    slug: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Boost productivity with the Pomodoro Technique — 25-minute focus sessions with short breaks.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🍅",
    keywords: ["pomodoro", "timer", "focus", "productivity", "work", "break", "technique"],
  },
  {
    slug: "working-hours-calculator",
    name: "Working Hours Calculator",
    description: "Calculate total working hours per day and week with break time deductions.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🕐",
    keywords: ["working hours", "work time", "hours", "break", "overtime", "calculator", "schedule"],
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    description: "Count down to any future date and time — events, deadlines, holidays, and more.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "⏳",
    keywords: ["countdown", "timer", "date", "event", "deadline", "days", "hours", "minutes"],
  },
  // Health (new batch)
  {
    slug: "calorie-burn-calculator",
    name: "Calorie Burn Calculator",
    description: "Estimate calories burned during exercise based on activity type, duration, and weight.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🔥",
    keywords: ["calories", "burn", "exercise", "activity", "met", "fitness", "calculator"],
  },
  {
    slug: "heart-rate-zone",
    name: "Heart Rate Zone Calculator",
    description: "Calculate your 5 training heart rate zones based on age and resting heart rate.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "❤️",
    keywords: ["heart rate", "zone", "training", "max hr", "cardio", "fitness", "karvonen"],
  },
  {
    slug: "sleep-cycle-calculator",
    name: "Sleep Cycle Calculator",
    description: "Find the best bedtime or wake-up time based on 90-minute sleep cycles.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "😴",
    keywords: ["sleep", "cycle", "wake up", "bedtime", "90 minutes", "rem", "calculator"],
  },
];

export const categories: Category[] = [
  {
    slug: "developer",
    name: "Developer Tools",
    description: "Essential tools for developers: JSON, Base64, UUID, hashing, and more.",
    icon: "💻",
    tools: tools.filter((t) => t.categorySlug === "developer"),
  },
  {
    slug: "converters",
    name: "Unit Converters",
    description: "Convert between units of length, weight, temperature, and more.",
    icon: "🔄",
    tools: tools.filter((t) => t.categorySlug === "converters"),
  },
  {
    slug: "text",
    name: "Text Tools",
    description: "Tools for text manipulation, counting, and conversion.",
    icon: "✍️",
    tools: tools.filter((t) => t.categorySlug === "text"),
  },
  {
    slug: "finance",
    name: "Finance Tools",
    description: "Calculators for interest, percentages, loans, and investments.",
    icon: "💰",
    tools: tools.filter((t) => t.categorySlug === "finance"),
  },
  {
    slug: "health",
    name: "Health Tools",
    description: "Health calculators for BMI, calories, and fitness metrics.",
    icon: "❤️",
    tools: tools.filter((t) => t.categorySlug === "health"),
  },
  {
    slug: "time",
    name: "Time Tools",
    description: "Time zone converters, age calculators, and date utilities.",
    icon: "⏰",
    tools: tools.filter((t) => t.categorySlug === "time"),
  },
  {
    slug: "math",
    name: "Math Tools",
    description: "Calculators for equations, number theory, and scientific computing.",
    icon: "🧮",
    tools: tools.filter((t) => t.categorySlug === "math"),
  },
];

export function getToolBySlug(slug: string): Tool | undefined {
  return tools.find((t) => t.slug === slug);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getToolsByCategory(categorySlug: string): Tool[] {
  return tools.filter((t) => t.categorySlug === categorySlug);
}
