import type { Tool } from "./types";

export const converterTools: Tool[] = [
  {
    slug: "length-converter",
    name: "Length Converter",
    description: "Convert between meters, feet, inches, miles, kilometers, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F4CF}",
    keywords: ["length", "convert", "meter", "feet", "inch", "mile", "kilometer"],
  },
  {
    slug: "weight-converter",
    name: "Weight Converter",
    description: "Convert between kilograms, pounds, ounces, grams, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u2696\uFE0F",
    keywords: ["weight", "mass", "kg", "lbs", "ounce", "gram", "convert"],
  },
  {
    slug: "temperature-converter",
    name: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F321}\uFE0F",
    keywords: ["temperature", "celsius", "fahrenheit", "kelvin", "convert"],
  },
  {
    slug: "data-storage-converter",
    name: "Data Storage Converter",
    description: "Convert between bytes, kilobytes, megabytes, gigabytes, terabytes, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F4BE}",
    keywords: ["bytes", "kb", "mb", "gb", "tb", "storage", "convert", "data size"],
  },
  {
    slug: "speed-converter",
    name: "Speed Converter",
    description: "Convert between km/h, mph, m/s, knots, and other speed units.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F680}",
    keywords: ["speed", "velocity", "km/h", "mph", "m/s", "knots", "convert"],
  },
  {
    slug: "area-converter",
    name: "Area Converter",
    description: "Convert between square meters, square feet, acres, hectares, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u2B1C",
    keywords: ["area", "square meter", "square foot", "acre", "hectare", "convert"],
  },
  {
    slug: "volume-converter",
    name: "Volume Converter",
    description: "Convert between liters, gallons, fluid ounces, cubic meters, and more.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F9CA}",
    keywords: ["volume", "liter", "gallon", "fluid ounce", "cubic meter", "convert"],
  },
  {
    slug: "angle-converter",
    name: "Angle Converter",
    description: "Convert between degrees, radians, gradians, and milliradians.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F4D0}",
    keywords: ["angle", "degrees", "radians", "gradians", "milliradians", "convert"],
  },
  {
    slug: "pressure-converter",
    name: "Pressure Converter",
    description: "Convert between Pascal, bar, PSI, atm, mmHg, and kPa.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F321}",
    keywords: ["pressure", "pascal", "bar", "psi", "atm", "mmhg", "kpa", "convert"],
  },
  {
    slug: "fuel-efficiency-converter",
    name: "Fuel Efficiency Converter",
    description: "Convert between km/L, mpg (US/UK), and L/100km fuel consumption units.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u26FD",
    keywords: ["fuel", "mpg", "km/l", "l/100km", "efficiency", "consumption", "convert"],
  },
  {
    slug: "energy-converter",
    name: "Energy Converter",
    description: "Convert between joules, calories, kilocalories, kWh, BTU, and electronvolts.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u26A1",
    keywords: ["energy", "joule", "calorie", "kwh", "btu", "electronvolt", "convert"],
  },
  {
    slug: "power-converter",
    name: "Power Converter",
    description: "Convert between watts, kilowatts, megawatts, horsepower, and BTU/hr.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F50C}",
    keywords: ["power", "watt", "kilowatt", "horsepower", "btu", "convert"],
  },
  {
    slug: "cooking-converter",
    name: "Cooking Unit Converter",
    description: "Convert between cups, tablespoons, teaspoons, milliliters, grams, and ounces for cooking.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F944}",
    keywords: ["cooking", "cup", "tablespoon", "teaspoon", "ml", "gram", "ounce", "recipe", "convert"],
  },
  {
    slug: "time-unit-converter",
    name: "Time Unit Converter",
    description: "Convert between seconds, minutes, hours, days, weeks, months, and years.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u23F1",
    keywords: ["time", "seconds", "minutes", "hours", "days", "weeks", "months", "years", "convert"],
  },
  {
    slug: "torque-converter",
    name: "Torque Converter",
    description: "Convert between Newton-meters, foot-pounds, kilogram-force meters, and more torque units.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F529}",
    keywords: ["torque", "newton meter", "foot pound", "kgf", "moment", "force", "convert"],
  },
  {
    slug: "illuminance-converter",
    name: "Illuminance Converter",
    description: "Convert between lux, foot-candle, and phot illuminance units.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "\u{1F4A1}",
    keywords: ["illuminance", "lux", "foot-candle", "phot", "light", "brightness", "convert"],
  },
  {
    slug: "frequency-converter",
    name: "Frequency Converter",
    description: "Convert between Hz, kHz, MHz, GHz, THz, and RPM.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "〜",
    keywords: ["frequency", "hz", "khz", "mhz", "ghz", "thz", "rpm", "hertz", "convert"],
  },
  {
    slug: "shoe-size-converter",
    name: "Shoe Size Converter",
    description: "Convert shoe sizes between US, EU, UK, Japan, and centimeters.",
    category: "Unit Converters",
    categorySlug: "converters",
    icon: "👟",
    keywords: ["shoe size", "us", "eu", "uk", "japan", "cm", "convert", "footwear", "sizing"],
  },
];
