import type { Tool } from "./types";

export const developerTools: Tool[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify JSON data with syntax highlighting.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "{ }",
    keywords: ["json", "format", "validate", "beautify", "minify", "pretty print"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate random UUIDs (v4) for use in your applications.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F511}",
    keywords: ["uuid", "guid", "unique", "identifier", "random", "v4"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode text or files to Base64 and decode Base64 strings.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "64",
    keywords: ["base64", "encode", "decode", "binary", "text"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode and decode URLs and query parameters for safe transmission.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F517}",
    keywords: ["url", "encode", "decode", "percent", "uri", "query string"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate MD5, SHA-256, and SHA-512 cryptographic hashes.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "#",
    keywords: ["hash", "md5", "sha256", "sha512", "checksum", "crypto"],
  },
  {
    slug: "jwt-decoder",
    name: "JWT Decoder",
    description: "Decode and inspect JSON Web Token payloads without signature verification.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "JWT",
    keywords: ["jwt", "json web token", "decode", "payload", "auth", "bearer"],
  },
  {
    slug: "color-converter",
    name: "Color Converter",
    description: "Convert colors between HEX, RGB, and HSL formats instantly.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F3A8}",
    keywords: ["color", "hex", "rgb", "hsl", "converter", "palette", "css color"],
  },
  {
    slug: "number-base-converter",
    name: "Number Base Converter",
    description: "Convert numbers between binary, octal, decimal, and hexadecimal.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "01",
    keywords: ["binary", "octal", "decimal", "hexadecimal", "base", "convert", "number base"],
  },
  {
    slug: "regex-tester",
    name: "RegEx Tester",
    description: "Test and debug regular expressions with live match highlighting.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: ".*",
    keywords: ["regex", "regular expression", "test", "match", "pattern", "debug"],
  },
  {
    slug: "csv-json",
    name: "CSV \u2194 JSON Converter",
    description: "Convert CSV data to JSON and JSON arrays back to CSV format.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "CSV",
    keywords: ["csv", "json", "convert", "data", "spreadsheet", "table"],
  },
  {
    slug: "diff-checker",
    name: "Diff Checker",
    description: "Compare two texts and highlight the differences line by line.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u00B1",
    keywords: ["diff", "compare", "text", "difference", "changes", "patch"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder Lorem Ipsum text for design and development.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u00B6",
    keywords: ["lorem ipsum", "placeholder", "text", "generate", "dummy", "filler"],
  },
  {
    slug: "html-encoder",
    name: "HTML Encoder / Decoder",
    description: "Encode special characters to HTML entities and decode them back.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "</>",
    keywords: ["html", "encode", "decode", "entities", "escape", "unescape"],
  },
  {
    slug: "yaml-json",
    name: "YAML \u2194 JSON Converter",
    description: "Convert between YAML and JSON formats instantly.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u21CC",
    keywords: ["yaml", "json", "convert", "configuration", "config", "devops"],
  },
  {
    slug: "cron-parser",
    name: "Cron Expression Parser",
    description: "Parse and explain cron expressions with next scheduled execution times.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u23F1",
    keywords: ["cron", "crontab", "schedule", "expression", "parse", "unix", "linux"],
  },
  {
    slug: "json-to-typescript",
    name: "JSON to TypeScript",
    description: "Convert JSON objects to TypeScript interfaces automatically.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "TS",
    keywords: ["json", "typescript", "interface", "type", "convert", "schema", "generate"],
  },
  {
    slug: "sql-formatter",
    name: "SQL Formatter",
    description: "Format and beautify SQL queries for better readability.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "SQL",
    keywords: ["sql", "format", "query", "beautify", "database", "indent"],
  },
  {
    slug: "string-escape",
    name: "String Escape / Unescape",
    description: "Escape and unescape strings for JSON, JavaScript, and HTML contexts.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\\n",
    keywords: ["escape", "unescape", "string", "json", "javascript", "html", "backslash"],
  },
  {
    slug: "favicon-generator",
    name: "Favicon Generator",
    description: "Generate favicon PNG files from text, emoji, or initials for your website.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F5BC}\uFE0F",
    keywords: ["favicon", "icon", "png", "emoji", "website", "generate", "logo"],
  },
  {
    slug: "http-status-codes",
    name: "HTTP Status Code Reference",
    description: "Look up HTTP status codes with descriptions, use cases, and examples.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F310}",
    keywords: ["http", "status", "code", "404", "200", "500", "rest", "api", "reference"],
  },
  {
    slug: "markdown-table-generator",
    name: "Markdown Table Generator",
    description: "Build Markdown tables visually and copy the formatted output instantly.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F4CB}",
    keywords: ["markdown", "table", "generator", "grid", "column", "row", "format"],
  },
  {
    slug: "image-base64",
    name: "Image to Base64",
    description: "Convert images to Base64 Data URL for embedding directly in HTML or CSS.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F5BC}",
    keywords: ["image", "base64", "data url", "encode", "embed", "html", "css", "png", "jpg"],
  },
  {
    slug: "css-unit-converter",
    name: "CSS Unit Converter",
    description: "Convert between px, em, rem, vw, vh, pt, and cm for responsive web design.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F4D0}",
    keywords: ["css", "px", "em", "rem", "vw", "vh", "unit", "convert", "responsive", "web design"],
  },
  {
    slug: "chmod-calculator",
    name: "Chmod Calculator",
    description: "Calculate Unix file permissions. Convert between octal notation and symbolic rwx format.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F510}",
    keywords: ["chmod", "unix", "permissions", "octal", "rwx", "linux", "file", "symbolic"],
  },
  {
    slug: "number-to-words",
    name: "Number to Words",
    description: "Convert numbers to English words (e.g. 1234 \u2192 one thousand two hundred thirty-four).",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "123",
    keywords: ["number", "words", "convert", "english", "spell", "write out"],
  },
  {
    slug: "color-palette",
    name: "Color Palette Generator",
    description: "Generate complementary, analogous, triadic, and other color palettes from a base color.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F3A8}",
    keywords: ["color", "palette", "complementary", "analogous", "triadic", "hsl", "hex", "design"],
  },
  {
    slug: "qr-code-generator",
    name: "QR Code Generator",
    description: "Generate QR codes from any text or URL instantly.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u25A6",
    keywords: ["qr code", "qr", "barcode", "generate", "url", "text", "scan"],
  },
  {
    slug: "aspect-ratio-calculator",
    name: "Aspect Ratio Calculator",
    description: "Calculate aspect ratios and scale dimensions while maintaining proportions.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u2B1A",
    keywords: ["aspect ratio", "resolution", "width", "height", "scale", "16:9", "4:3"],
  },
  {
    slug: "color-gradient-generator",
    name: "CSS Gradient Generator",
    description: "Create beautiful CSS linear and radial gradients with a visual editor.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F308}",
    keywords: ["gradient", "css", "linear", "radial", "color", "background", "generator"],
  },
  {
    slug: "morse-code-converter",
    name: "Morse Code Converter",
    description: "Convert text to Morse code and decode Morse code back to text.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u00B7\u2212",
    keywords: ["morse code", "morse", "convert", "encode", "decode", "dots", "dashes"],
  },
  {
    slug: "ip-subnet-calculator",
    name: "IP Subnet Calculator",
    description: "Calculate subnet mask, network address, broadcast, and host range for any CIDR block.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "\u{1F310}",
    keywords: ["ip", "subnet", "cidr", "network", "mask", "broadcast", "host", "networking"],
  },
  {
    slug: "ascii-art",
    name: "ASCII Art Generator",
    description: "Convert text to ASCII art using classic FIGlet-style block letter fonts.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "A\u2593",
    keywords: ["ascii", "art", "text", "figlet", "banner", "block", "letter", "font", "generate"],
  },
  {
    slug: "xml-formatter",
    name: "XML Formatter",
    description: "Format, validate, and minify XML documents with syntax highlighting.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "XML",
    keywords: ["xml", "format", "validate", "beautify", "minify", "pretty print", "html"],
  },
  {
    slug: "jwt-generator",
    name: "JWT Generator",
    description: "Generate signed JWT tokens with custom header, payload, and secret key.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "JWT",
    keywords: ["jwt", "json web token", "generate", "sign", "hs256", "auth", "bearer", "token"],
  },
  {
    slug: "cipher-tool",
    name: "Cipher Tool",
    description: "Encode and decode text with Caesar, ROT13, and Vigenère ciphers.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "🔐",
    keywords: ["cipher", "caesar", "rot13", "vigenere", "encrypt", "decrypt", "encode", "decode", "cryptography"],
  },
  {
    slug: "mime-type-lookup",
    name: "MIME Type Lookup",
    description: "Look up MIME types by file extension or find extensions for a given MIME type.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "📄",
    keywords: ["mime", "type", "content-type", "file extension", "media type", "http", "lookup"],
  },
  {
    slug: "color-blindness-simulator",
    name: "Color Blindness Simulator",
    description: "Preview how colors appear to people with different types of color vision deficiency.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "👁️",
    keywords: ["color blindness", "color vision", "protanopia", "deuteranopia", "tritanopia", "accessibility", "color deficiency"],
  },
  {
    slug: "json-diff",
    name: "JSON Diff",
    description: "Compare two JSON objects and highlight added, removed, and changed keys.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "⚖️",
    keywords: ["json", "diff", "compare", "difference", "object", "keys", "changes"],
  },
  {
    slug: "number-formatter",
    name: "Number Formatter",
    description: "Format numbers as currency, percentage, scientific notation, or with custom separators.",
    category: "Developer Tools",
    categorySlug: "developer",
    icon: "🔢",
    keywords: ["number", "format", "currency", "percentage", "scientific", "thousand separator", "decimal"],
  },
];
