import type { Tool } from "./types";

export const financeTools: Tool[] = [
  {
    slug: "compound-interest",
    name: "Compound Interest Calculator",
    description: "Calculate compound interest growth for investments over time.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "📈",
    keywords: ["compound interest", "investment", "calculator", "finance", "savings"],
  },
  {
    slug: "percentage-calculator",
    name: "Percentage Calculator",
    description: "Calculate percentages, percentage change, and tip amounts.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "%",
    keywords: ["percentage", "percent", "tip", "calculator", "math"],
  },
  {
    slug: "discount-calculator",
    name: "Discount Calculator",
    description: "Calculate sale prices, discount amounts, and savings instantly.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "🏷️",
    keywords: ["discount", "sale", "price", "savings", "percent off", "calculator"],
  },
  {
    slug: "loan-calculator",
    name: "Loan Calculator",
    description: "Calculate monthly payments, total interest, and amortization for loans.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "🏦",
    keywords: ["loan", "mortgage", "payment", "interest", "amortization", "calculator"],
  },
  {
    slug: "roi-calculator",
    name: "ROI Calculator",
    description: "Calculate return on investment and annualized ROI for any investment.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "📊",
    keywords: ["roi", "return on investment", "profit", "investment", "calculator"],
  },
  {
    slug: "tip-calculator",
    name: "Tip Calculator",
    description: "Calculate tip amounts and split the bill between multiple people.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "💵",
    keywords: ["tip", "bill", "split", "restaurant", "calculator", "gratuity", "per person"],
  },
  {
    slug: "savings-goal-calculator",
    name: "Savings Goal Calculator",
    description: "Calculate how much you need to save each month to reach your financial goal.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "🏦",
    keywords: ["savings", "goal", "monthly", "investment", "interest", "target", "finance"],
  },
  {
    slug: "inflation-calculator",
    name: "Inflation Calculator",
    description: "Calculate the real value of money over time based on inflation rate.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "📈",
    keywords: ["inflation", "purchasing power", "cpi", "real value", "money", "finance"],
  },
  {
    slug: "break-even-calculator",
    name: "Break-Even Calculator",
    description: "Find the break-even point for your business based on costs and revenue.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "⚖️",
    keywords: ["break-even", "fixed cost", "variable cost", "revenue", "profit", "business"],
  },
  {
    slug: "vat-calculator",
    name: "VAT Calculator",
    description: "Add or remove VAT/tax from a price. Supports custom tax rates for any country.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "🧾",
    keywords: ["vat", "tax", "gst", "sales tax", "price", "calculator", "include", "exclude"],
  },
  {
    slug: "currency-converter",
    name: "Currency Converter",
    description: "Convert between major world currencies using reference exchange rates.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "💱",
    keywords: ["currency", "exchange rate", "convert", "usd", "eur", "gbp", "jpy", "forex"],
  },
  {
    slug: "net-worth-calculator",
    name: "Net Worth Calculator",
    description: "Calculate your total net worth by listing your assets and liabilities.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "💰",
    keywords: ["net worth", "assets", "liabilities", "wealth", "finance", "calculator", "balance sheet"],
  },
  {
    slug: "hourly-to-salary",
    name: "Hourly to Salary Converter",
    description: "Convert hourly wage to annual, monthly, and weekly salary — and vice versa.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "💼",
    keywords: ["hourly", "salary", "wage", "annual", "monthly", "convert", "income", "pay"],
  },
  {
    slug: "tax-bracket-calculator",
    name: "Tax Bracket Calculator",
    description: "Estimate US federal income tax, effective rate, and marginal rate for any income.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "🧾",
    keywords: ["tax", "income tax", "federal", "bracket", "irs", "marginal rate", "effective rate"],
  },
  {
    slug: "stock-profit-calculator",
    name: "Stock Profit Calculator",
    description: "Calculate profit, loss, and return on investment for stock trades.",
    category: "Finance Tools",
    categorySlug: "finance",
    icon: "📈",
    keywords: ["stock", "profit", "loss", "roi", "shares", "buy", "sell", "investment", "return"],
  },
];
