import type { Tool } from "./types";

export const healthTools: Tool[] = [
  {
    slug: "bmi-calculator",
    name: "BMI Calculator",
    description: "Calculate Body Mass Index with metric and imperial units.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🏃",
    keywords: ["bmi", "body mass index", "health", "weight", "height"],
  },
  {
    slug: "tdee-calculator",
    name: "TDEE Calculator",
    description: "Calculate your Total Daily Energy Expenditure and daily calorie needs.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🔥",
    keywords: ["tdee", "calories", "bmr", "energy", "diet", "nutrition", "calculator"],
  },
  {
    slug: "ideal-weight",
    name: "Ideal Weight Calculator",
    description: "Calculate your ideal body weight based on height using multiple formulas.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "⚖️",
    keywords: ["ideal weight", "healthy weight", "bmi", "height", "calculator"],
  },
  {
    slug: "body-fat",
    name: "Body Fat Calculator",
    description: "Estimate body fat percentage using the U.S. Navy method.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "📐",
    keywords: ["body fat", "body fat percentage", "navy method", "fitness", "calculator"],
  },
  {
    slug: "running-pace",
    name: "Running Pace Calculator",
    description: "Calculate running pace, speed, time, and distance for any race distance.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🏃",
    keywords: ["running", "pace", "marathon", "5k", "10k", "speed", "distance", "time", "race"],
  },
  {
    slug: "water-intake",
    name: "Water Intake Calculator",
    description: "Calculate your recommended daily water intake based on weight and activity level.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "💧",
    keywords: ["water", "hydration", "intake", "daily", "health", "calculator", "drink"],
  },
  {
    slug: "calorie-burn-calculator",
    name: "Calorie Burn Calculator",
    description: "Estimate calories burned during exercise based on activity type, duration, and weight.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🔥",
    keywords: ["calories", "burn", "exercise", "activity", "met", "fitness", "calculator"],
  },
  {
    slug: "heart-rate-zone",
    name: "Heart Rate Zone Calculator",
    description: "Calculate your 5 training heart rate zones based on age and resting heart rate.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "❤️",
    keywords: ["heart rate", "zone", "training", "max hr", "cardio", "fitness", "karvonen"],
  },
  {
    slug: "sleep-cycle-calculator",
    name: "Sleep Cycle Calculator",
    description: "Find the best bedtime or wake-up time based on 90-minute sleep cycles.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "😴",
    keywords: ["sleep", "cycle", "wake up", "bedtime", "90 minutes", "rem", "calculator"],
  },
  {
    slug: "protein-calculator",
    name: "Protein Intake Calculator",
    description: "Calculate your recommended daily protein intake based on weight, goal, and activity level.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🥩",
    keywords: ["protein", "intake", "daily", "muscle", "diet", "nutrition", "calculator", "macro"],
  },
  {
    slug: "blood-pressure-checker",
    name: "Blood Pressure Checker",
    description: "Enter your blood pressure reading and see which category it falls into (normal, high, etc.).",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🩺",
    keywords: ["blood pressure", "systolic", "diastolic", "hypertension", "health", "checker", "mmhg"],
  },
  {
    slug: "macro-calculator",
    name: "Macro Calculator",
    description: "Calculate daily carbohydrate, protein, and fat targets based on your calorie goal.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🥗",
    keywords: ["macro", "protein", "carbs", "fat", "diet", "nutrition", "calorie", "calculator"],
  },
  {
    slug: "menstrual-cycle-calculator",
    name: "Menstrual Cycle Calculator",
    description: "Predict your next period and fertile window based on cycle length and last period date.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "📆",
    keywords: ["menstrual", "period", "cycle", "fertile", "ovulation", "fertility", "calculator"],
  },
  {
    slug: "due-date-calculator",
    name: "Pregnancy Due Date Calculator",
    description: "Calculate your estimated due date using Naegele's rule and track key pregnancy milestones.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🤰",
    keywords: ["pregnancy", "due date", "naegele", "gestational age", "trimester", "baby", "calculator"],
  },
  {
    slug: "one-rep-max-calculator",
    name: "One Rep Max Calculator",
    description: "Estimate your 1RM maximum lift using Epley, Brzycki, and other popular formulas.",
    category: "Health Tools",
    categorySlug: "health",
    icon: "🏋️",
    keywords: ["1rm", "one rep max", "weightlifting", "strength", "epley", "brzycki", "fitness", "gym"],
  },
];
