import type { Tool } from "./types";

export const mathTools: Tool[] = [
  {
    slug: "scientific-calculator",
    name: "Scientific Calculator",
    description: "Advanced calculator with trigonometry, logarithms, powers, and more.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "🧮",
    keywords: ["calculator", "scientific", "sin", "cos", "tan", "log", "sqrt", "math"],
  },
  {
    slug: "gcd-lcm",
    name: "GCD & LCM Calculator",
    description: "Calculate the Greatest Common Divisor and Least Common Multiple of multiple numbers.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "÷",
    keywords: ["gcd", "lcm", "greatest common divisor", "least common multiple", "math", "number theory"],
  },
  {
    slug: "quadratic-solver",
    name: "Quadratic Equation Solver",
    description: "Solve quadratic equations ax² + bx + c = 0 with step-by-step solutions.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "x²",
    keywords: ["quadratic", "equation", "solver", "roots", "discriminant", "polynomial", "math"],
  },
  {
    slug: "statistics-calculator",
    name: "Statistics Calculator",
    description: "Calculate mean, median, mode, standard deviation, variance, and more.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "σ",
    keywords: ["statistics", "mean", "median", "mode", "standard deviation", "variance", "calculator"],
  },
  {
    slug: "fraction-calculator",
    name: "Fraction Calculator",
    description: "Add, subtract, multiply, and divide fractions with step-by-step solutions.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "½",
    keywords: ["fraction", "numerator", "denominator", "add", "subtract", "multiply", "divide", "simplify"],
  },
  {
    slug: "roman-numeral-converter",
    name: "Roman Numeral Converter",
    description: "Convert between Arabic numbers and Roman numerals instantly.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "Ⅻ",
    keywords: ["roman numeral", "arabic", "convert", "number", "roman"],
  },
  {
    slug: "triangle-calculator",
    name: "Triangle Calculator",
    description: "Solve any triangle given sides and angles (SSS, SAS, ASA, AAS). Get area and perimeter.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "△",
    keywords: ["triangle", "solve", "sides", "angles", "area", "perimeter", "sss", "sas", "asa", "aas", "trigonometry"],
  },
  {
    slug: "prime-checker",
    name: "Prime Number Checker",
    description: "Check if a number is prime and find all prime numbers up to a limit.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "🔢",
    keywords: ["prime", "number", "checker", "sieve", "factor", "divisible", "prime numbers"],
  },
  {
    slug: "combinations-permutations",
    name: "Combinations & Permutations",
    description: "Calculate nCr (combinations) and nPr (permutations) with step-by-step solutions.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "⊂",
    keywords: ["combination", "permutation", "ncr", "npr", "factorial", "probability", "counting"],
  },
  {
    slug: "prime-factorizer",
    name: "Prime Checker & Factorizer",
    description: "Check if a number is prime and find its prime factorization.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "ℙ",
    keywords: ["prime", "factor", "factorization", "prime number", "sieve", "divisor"],
  },
  {
    slug: "matrix-calculator",
    name: "Matrix Calculator",
    description: "Add, multiply, transpose, and find the determinant of 2×2 and 3×3 matrices.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "⊞",
    keywords: ["matrix", "determinant", "multiply", "transpose", "inverse", "linear algebra"],
  },
  {
    slug: "number-sequence",
    name: "Number Sequence Generator",
    description: "Generate arithmetic, geometric, Fibonacci, and prime number sequences.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "…",
    keywords: ["sequence", "arithmetic", "geometric", "fibonacci", "prime", "series", "pattern"],
  },
  {
    slug: "proportion-solver",
    name: "Proportion Solver",
    description: "Solve proportions and ratios — find the missing value in a/b = c/d.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "∝",
    keywords: ["proportion", "ratio", "solve", "cross multiply", "a/b=c/d", "missing value"],
  },
  {
    slug: "unit-price-calculator",
    name: "Unit Price Calculator",
    description: "Compare prices per unit to find the best deal between different package sizes.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "🏷",
    keywords: ["unit price", "price per unit", "compare", "best deal", "cost", "shopping", "calculator"],
  },
  {
    slug: "log-calculator",
    name: "Logarithm Calculator",
    description: "Calculate logarithms in any base — natural log (ln), log base 10, or custom base.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "㏒",
    keywords: ["logarithm", "log", "ln", "natural log", "base 10", "calculator", "math", "exponent"],
  },
  {
    slug: "binary-calculator",
    name: "Binary Calculator",
    description: "Perform arithmetic and bitwise operations on binary, decimal, and hexadecimal numbers.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "10",
    keywords: ["binary", "hex", "bitwise", "AND", "OR", "XOR", "NOT", "shift", "calculator"],
  },
  {
    slug: "vector-calculator",
    name: "Vector Calculator",
    description: "Calculate 2D and 3D vector addition, subtraction, dot product, cross product, and magnitude.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "→",
    keywords: ["vector", "dot product", "cross product", "magnitude", "2d", "3d", "math", "physics"],
  },
  {
    slug: "geometry-calculator",
    name: "Geometry Calculator",
    description: "Calculate area, perimeter, and volume of circles, rectangles, triangles, spheres, and more.",
    category: "Math Tools",
    categorySlug: "math",
    icon: "📐",
    keywords: ["geometry", "area", "perimeter", "volume", "circle", "rectangle", "triangle", "sphere", "cylinder"],
  },
  {
    slug: "ohm-law-calculator",
    name: "Ohm's Law Calculator",
    description: "Calculate voltage, current, resistance, and power using Ohm's Law (V = IR).",
    category: "Math Tools",
    categorySlug: "math",
    icon: "Ω",
    keywords: ["ohm", "voltage", "current", "resistance", "power", "v=ir", "electronics", "circuit", "calculator"],
  },
];
