import type { Tool } from "./types";

export const textTools: Tool[] = [
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    description: "Count words, characters, sentences, and paragraphs in your text.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "✍️",
    keywords: ["word count", "character count", "text", "counter", "writing"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text to UPPERCASE, lowercase, Title Case, camelCase, and more.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "Aa",
    keywords: ["case", "uppercase", "lowercase", "title case", "camelcase", "text convert"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, secure passwords with customizable options.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🔒",
    keywords: ["password", "generate", "secure", "random", "strong", "security"],
  },
  {
    slug: "markdown-preview",
    name: "Markdown Preview",
    description: "Write Markdown and preview the rendered output in real time.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "MD",
    keywords: ["markdown", "preview", "render", "html", "editor", "md"],
  },
  {
    slug: "slug-generator",
    name: "Slug Generator",
    description: "Convert any text into a clean, URL-friendly slug.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🔗",
    keywords: ["slug", "url", "permalink", "seo", "text", "convert"],
  },
  {
    slug: "text-repeater",
    name: "Text Repeater",
    description: "Repeat any text or character a specified number of times.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "↺",
    keywords: ["repeat", "text", "duplicate", "loop", "generator"],
  },
  {
    slug: "text-to-binary",
    name: "Text to Binary / Hex",
    description: "Convert text to binary, hexadecimal, octal, and decimal encodings.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "01",
    keywords: ["binary", "hex", "hexadecimal", "text", "convert", "encode", "ascii", "octal"],
  },
  {
    slug: "random-name-generator",
    name: "Random Name Generator",
    description: "Generate random first names, last names, or full names for testing and placeholders.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "👤",
    keywords: ["name", "random", "generate", "first name", "last name", "fake", "placeholder"],
  },
  {
    slug: "text-to-speech",
    name: "Text to Speech",
    description: "Convert text to speech using your browser's built-in speech synthesis engine.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🔊",
    keywords: ["text to speech", "tts", "speech", "voice", "read aloud", "synthesize", "audio"],
  },
  {
    slug: "word-frequency-counter",
    name: "Word Frequency Counter",
    description: "Analyze text and count how often each word appears, ranked by frequency.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "📊",
    keywords: ["word frequency", "count", "analyze", "text", "rank", "occurrence", "statistics"],
  },
  {
    slug: "find-replace",
    name: "Find & Replace",
    description: "Find and replace text with plain text or regex patterns. Supports case-insensitive matching.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🔍",
    keywords: ["find", "replace", "regex", "text", "search", "substitute", "pattern"],
  },
  {
    slug: "text-cleaner",
    name: "Text Cleaner",
    description: "Remove extra spaces, empty lines, special characters, and HTML tags from text.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🧹",
    keywords: ["clean", "text", "remove", "whitespace", "spaces", "html", "strip", "trim"],
  },
  {
    slug: "text-sorter",
    name: "Text Sorter",
    description: "Sort lines of text alphabetically, by length, or randomly.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "↕",
    keywords: ["sort", "text", "lines", "alphabetical", "order", "arrange"],
  },
  {
    slug: "emoji-picker",
    name: "Emoji Picker",
    description: "Browse, search, and copy emojis to your clipboard instantly.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "😀",
    keywords: ["emoji", "picker", "copy", "search", "unicode", "emoticon"],
  },
  {
    slug: "line-deduplicator",
    name: "Line Deduplicator",
    description: "Remove duplicate lines from text with options for case sensitivity and sorting.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "⊟",
    keywords: ["duplicate", "lines", "remove", "unique", "deduplicate", "text"],
  },
  {
    slug: "anagram-solver",
    name: "Anagram Solver",
    description: "Check if two words or phrases are anagrams of each other and find all anagrams.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🔀",
    keywords: ["anagram", "word", "letter", "rearrange", "checker", "solver", "puzzle"],
  },
  {
    slug: "palindrome-checker",
    name: "Palindrome Checker",
    description: "Check if a word, phrase, or number reads the same forwards and backwards.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "↔",
    keywords: ["palindrome", "word", "reverse", "checker", "text", "phrase"],
  },
  {
    slug: "text-statistics",
    name: "Text Readability Analyzer",
    description: "Analyze text readability with Flesch score, average sentence length, and more.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "📊",
    keywords: ["readability", "flesch", "reading ease", "gunning fog", "text analysis", "grade level"],
  },
  {
    slug: "speech-to-text",
    name: "Speech to Text",
    description: "Convert speech to text using your browser's built-in voice recognition engine.",
    category: "Text Tools",
    categorySlug: "text",
    icon: "🎙️",
    keywords: ["speech", "voice", "recognition", "transcribe", "dictate", "microphone", "text"],
  },
];
