import type { Tool } from "./types";

export const timeTools: Tool[] = [
  {
    slug: "age-calculator",
    name: "Age Calculator",
    description: "Calculate exact age in years, months, and days from a birth date.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🎂",
    keywords: ["age", "birthday", "date", "calculate", "years", "months"],
  },
  {
    slug: "timezone-converter",
    name: "Timezone Converter",
    description: "Convert time between different time zones around the world.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🌍",
    keywords: ["timezone", "time zone", "convert", "world time", "utc", "gmt"],
  },
  {
    slug: "unix-timestamp",
    name: "Unix Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "⏱️",
    keywords: ["unix", "timestamp", "epoch", "date", "convert", "time", "posix"],
  },
  {
    slug: "date-difference",
    name: "Date Difference Calculator",
    description: "Calculate the exact number of days, weeks, and months between two dates.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "📅",
    keywords: ["date", "difference", "days between", "calculate", "calendar", "duration"],
  },
  {
    slug: "time-duration",
    name: "Time Duration Calculator",
    description: "Add or subtract hours, minutes, and seconds to calculate time durations.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "⏳",
    keywords: ["time", "duration", "hours", "minutes", "seconds", "add", "subtract"],
  },
  {
    slug: "pomodoro-timer",
    name: "Pomodoro Timer",
    description: "Boost productivity with the Pomodoro Technique — 25-minute focus sessions with short breaks.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🍅",
    keywords: ["pomodoro", "timer", "focus", "productivity", "work", "break", "technique"],
  },
  {
    slug: "working-hours-calculator",
    name: "Working Hours Calculator",
    description: "Calculate total working hours per day and week with break time deductions.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🕐",
    keywords: ["working hours", "work time", "hours", "break", "overtime", "calculator", "schedule"],
  },
  {
    slug: "countdown-timer",
    name: "Countdown Timer",
    description: "Count down to any future date and time — events, deadlines, holidays, and more.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "⏳",
    keywords: ["countdown", "timer", "date", "event", "deadline", "days", "hours", "minutes"],
  },
  {
    slug: "meeting-planner",
    name: "Meeting Time Zone Planner",
    description: "Find the best meeting time across multiple time zones simultaneously.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🌍",
    keywords: ["meeting", "time zone", "world clock", "schedule", "international", "remote"],
  },
  {
    slug: "year-progress",
    name: "Year Progress",
    description: "See how much of the current year has passed and what's remaining.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "📅",
    keywords: ["year", "progress", "remaining", "days", "2025", "calendar", "time"],
  },
  {
    slug: "date-calculator",
    name: "Date Calculator",
    description: "Add or subtract days, weeks, months, or years from any date.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "🗓️",
    keywords: ["date", "add", "subtract", "days", "weeks", "months", "years", "calculate", "calendar"],
  },

  {
    slug: "business-days-calculator",
    name: "Business Days Calculator",
    description: "Count the number of working days between two dates, excluding weekends.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "📆",
    keywords: ["business days", "working days", "weekdays", "exclude weekends", "calendar", "date", "calculator"],
  },

  {
    slug: "stopwatch",
    name: "Stopwatch",
    description: "Precise stopwatch with lap recording, running in the foreground and background tab.",
    category: "Time Tools",
    categorySlug: "time",
    icon: "⏱️",
    keywords: ["stopwatch", "timer", "lap", "split", "time", "track", "running", "sport", "chronometer"],
  },
];